name: Paige Crum
description: Welcome
meta_description: "Paige Crum Portfolio Site"

markdown: redcarpet
extensions: [fenced_code_blocks]
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url: 'paigecrum.github.io'
author: 'Paige Crum'
email: 'paigecrum@gmail.com'
# github: 'paigecrum'
# twitter: 'paigecrum'